### ISSUE TITLE
Create 'Intro to Arduino" resources

### ISSUE THREAD

**Issue by daniel-packard** [CenWIDev/sumobot-resources#1]

**Comment by daniel-packard** [comment]
Draft coming together at: https://codepen.io/daniel-packard/live/Qorxye

**Comment by Erik-Bennett** [comment]
Do you know what IDE is available for a Chromebook? Just wondering as I lack a portable PC.

I did find many options, but I did find [ChromeDuino2](https://chrome.google.com/webstore/detail/chromeduino2/llclpgogfbmiicabgcfbndeokekmggpm). Will this work?

**Comment by daniel-packard** [comment]
Hmmm, I've never tried.. I'd be surprised if there isn't some way to use arduino on a chromebook.

I'd install ChromeDuino2, and bring it -- if it doesn't work, we can dig in at the work night

**Comment by daniel-packard** [comment]
presentation live at: https://codepen.io/daniel-packard/live/Qorxye
