### ISSUE TITLE
Decide on options for kits / bulk parts

### ISSUE THREAD

**Issue by daniel-packard** [CenWIDev/sumobot-resources#2]
We can use this issue as a place to discuss options for kits and bulk order parts

**Comment by daniel-packard** [comment]
Erik Bennet found this kit: 

- https://www.kickstarter.com/projects/tianli/moonbot-diy-kit-for-tinkering-with-modern-robotics/description

It's a kickstarter that hasn't fulfilled the orders for their backers yet.. but it looks great!

**Comment by Erik-Bennett** [comment]
What components will be standardized/limited and what will be left to creativity? For example, we require a specific selection of - microcontrollers, shields, sensors, and motors - while allowing any body, frame, non-destructive armaments, and locomotion mechanisms.

There are pros and cons for both ordering in bulk vs kits.  What components does the IDEA Center already have and are they application appropriate for the sumobots? If we already have some of the required parts, additional bulk parts might be best. If we're starting from scratch, kits might be.

I know there wasn't much interest from the group that met, but I'd like to see the LEGO class offered for the kiddos. Even if it doesn't generate a large competitive field, it would still be fun and could be an impactful learning experience.

**Comment by daniel-packard** [comment]
I'm thinking we should put very few restrictions on what people can use... I'm leaning towards kits to facilitate teaching/learning, but not to limit what people can experiment with.

I think LEGO would be a great platform to help get people up and running -- want to organize a "LEGO kit night"?

**Comment by Erik-Bennett** [comment]
Hmmm.... https://www.jsumo.com/
