### ISSUE TITLE
Decide on competition rules / guidelines

### ISSUE THREAD

**Issue by daniel-packard** [CenWIDev/sumobot-resources#3]
We can use this issue to discuss competition rules and guidelines

**Comment by daniel-packard** [comment]
A good starting point: 
* http://robogames.net/rules/all-sumo.php

**Comment by daniel-packard** [comment]
Also a good summary:  http://www.robotroom.com/SumoRules.html

**Comment by Erik-Bennett** [comment]
I'll type up a ruleset proposal for the LEGO sumobot class - with a younger audience in mind - this week. I'll see what institutional knowledge I can glean from other competitions' rules (FIRST, LEGO official, etc).

**Comment by Erik-Bennett** [comment]
I) I have a draft ruleset (based on other, established competitions) for the LEGO sumobot class.  We ran into issues with the size limitation of the [Unified Sumo Robot Rules](http://robogames.net/rules/all-sumo.php).  The 1kg mass limitation is easy to make, but the 15cm limitation on the footprint dimensions is less so.

  _PROS of 15cm * 15cm footprint rule_
  - center of gravity is shifted upward, which may make matches shorter and more interesting (pro); tipping outcomes will be increased, and static push offs reduced.
  - it forces builders to do unorthodox things and opt out of the "easy" builds (building low and wide is easy)

  _CONS of 15cm * 15cm footprint rule:_ 
  - excludes a number of interesting builds (e.g., any configuration with 3 large motors aligned in the same plane)
  - a small increase in the footprint dimensions increases build options

  We're going to take measurements tonight at our meeting and discuss the options. 

II) We need to set footprint and mass limits for the built-from-scratch class.  The original target was the _Unified mini class_, but it's clear that a base of 10cm * 10cm isn't easily achieved given our hardware. Similar pros and cons apply for changing these dimensions.

**Comment by daniel-packard** [comment]
My inclination is to have very lenient rules for this first competition... if you build a robot, and it fits in the ring (and isn't _grotesquely_ outside of some rough guidelines, 1kg + 15x15cm) -- let's battle 🤖

**Comment by Erik-Bennett** [comment]
That's sensible, given the challenges we've encountered and the learning curve. With the LEGOs, we have it a bit easier in that the building up a viable robot and code is quick; the rules are really just the guideposts for constructing and bettering their sumobots.

**Comment by wrentfrow** [comment]
I don't really care what the rules are and I don't care about winning.  Given the recent experience there's about a 50% chance the motors will rip the wheels right off our bot.  That said, my daughter and I have learned a lot and had a lot of fun and I'm willing to go pretty lenient.

**Comment by Erik-Bennett** [comment]
In a non-competitive setting such as ours, the rules are guideposts more than limitations.  The youths in our 4-H robotics club would be "out in the weeds" without a decent ruleset to keep them focused and on track.
