### ISSUE TITLE
Design and Construct the sumo bot arena 

### ISSUE THREAD

**Issue by daniel-packard** [CenWIDev/sumobot-resources#4]

**Comment by Erik-Bennett** [comment]
Will the 3D printer produce a suitably smooth surface finish? Most of the sumobots I've seen use some form of downward facing optical sensors, so a consistent surface for reflecting light is necessary (it's certainly possible to build robustness into the arena sensing system, but it would add complexity or cost). Mechanic clearances (surface-hugging defensive designs are common) and traction (wheel and tire selection become more important) need to be considered as well. I like the idea, and it may work perfectly well, but it adds some unknowns and potential complexity.

I have a router jig for cutting circles. I'll check to see if it will cut a large enough circle. Marshfield has multiple countertop manufacturers, at least one of which sells cut-rate offcuts. I could politely request the material as a donation (they may even be able to cut it for us); let me know if I should pursue this.

**Comment by daniel-packard** [comment]
I think using a router would definitely be a more practical approach. There will be other opportunities for us to use that giant 3D printer!

Yeah, I say please find out about getting donated materials and access to a router

**Comment by Erik-Bennett** [comment]
Will do - my circle jig should work.  Are we using a single Dohyo (ring) size? "Mini" and LEGO classes both call for the 77cm diameter circle.

**Comment by daniel-packard** [comment]
An arena sized for the mini class should be good

**Comment by Erik-Bennett** [comment]
I'll work on getting the rings material and making them early next week.  Based on the Robogames Unified Sumo Robot Rules - Dohyo requirements, I'll be looking for:
- Laminate/Melamine coated wood
- 1" total thickness
- paintable surface - I'm guessing a matte finish is preferable

I was thinking of creating second outer square section similar to that of a traditional Dohyo.  This would be layered underneath the ring and made from a from cheap, lightweight material. We could have sponsor logos or ???? to this area.

**Comment by daniel-packard** [comment]
Material specs sound good to me.

We should bounce the idea of "sponsor logos" off greg.. I'll try to pester him into getting on github so we can include him in the discussion.

**Comment by Erik-Bennett** [comment]
I've request a donation of scrap laminated countertop material. In keeping with the reduce/reuse/recycle ethos of the IDEA Center, I've specifically asked for offcuts that would otherwise be waste.  When I get the material, I'll cut the doyhos with my router. I'm a bit unsure how to apply the mark out the lines and paint them, but when I get that far, I'll bring them to Point.  I'm hoping to make 3 of them, one each for Rapids, Point, and Marshfield.

As it's been a while, I'll check in, in-person, tomorrow.  If needed, I'll check with the other countertop manufacturer here as well.

**Comment by Erik-Bennett** [comment]
I picked up enough material for 2 of the 77cm dohyos.  I'll cut them (outside) when it warms up next week.

**Comment by daniel-packard** [comment]
Awesome! 

Are there groups actively running paralell competitions in Rapids and Marshfield?? We should share resources

**Comment by Erik-Bennett** [comment]
I apologize. I've haven't gotten the invites out here, so I'm doing that right _now_. I have tried recruiting younger members for a LEGO class, but only have 1 team thus far.

**Comment by Erik-Bennett** [comment]
What's the best initial contact point for new, interested parties?

**Comment by Erik-Bennett** [comment]
The Rapids group is participating in the IDEA Center's event, but based on their Slack, they have lot of involvement. I'm making three rings so everyone has a practice ring; that, and I think they'll make good, tangible marketing pieces (or at least good conversation pieces) for each location.

I apologize as I've been slow in getting out the invites in Marshfield; I'm unaware of any tech groups here in Marshfield (mostly medical and heavy manufacturing). I have tried recruiting younger members for a LEGO class, but only have 1 team thus far.

**Comment by Erik-Bennett** [comment]
Would it be possible to using the big printer to create a 77cm outer-diameter ring, 1/4 in. thick?  Perhaps it could wrap the outside edge of the laminated wood to add durability and prevent damage to support surfaces. I could have my son draft the design and provide the STL file (great fair project for him).

**Comment by Erik-Bennett** [comment]
The rain and cold relented, so we finished the planning and rough cutting today. My jig won't cut a circle as large we need, so I'm building a larger jig. I was hoping they'd be done this week, but early next week seems more likely.
![Dohyo rough cuts](https://user-images.githubusercontent.com/48447386/57665114-49923500-75c0-11e9-8227-6b59421f4e67.jpg)

**Comment by Erik-Bennett** [comment]
Progress chart
- [x] Acquire wood
- [x] build larger circle cutting jig
- [x] cut circles
- [x] chamfer sharp edges (very slight chamfer, but a definite improvement)
- [x] sand and prep for paint
- [x] test paints
Paint test notes: partially done
- donated gallon of acrylic seems decent if a bit sticky; the tint looks darker when dry, which may be workable for the field - deep grayish black
- in testing, acrylic appears to be not resilient enough, scratches readily - may transfer paint to LEGO pieces that slide on the surface - should work for back and edges though
- [x] test paints with line sensor
- [x] report on findings
- [x] buy spray paint for plastic
- [x] buy primer for plastic (paint not adhering well)
- [x] buy high quality masking tape
- [x] build jig for marking paint region boundary
- [x] paint black region
- [x] paint white region
- [ ] acquire more epoxy
- [ ] acquire protective base material - rubber feet, cork, plastic, foam, suggestions??? to meet height requirements and protection of support surface
- [ ] epoxy holes/gaps in dohyo 2 (3 layer done - 1 to go, out of epoxy)
- [ ] finish epoxied spots (filling, smoothing, sanding)
- [ ] shikiri lines - basic or stylized? perhaps we could get an artist (or template) and use the logo Greg created
- [ ] create an outer protective ring (epoxy, 3-D printed?) - preferable translucent, but priority on durability and impact deadening
- [ ] embed LED tape under the outer ring, sync to hype music or ?? (next year?)

Note that some steps are necessary only for our LEGO robotics club dohyo; it will be transported frequently and placed on new wooden tables, so extra protection is needed.
