### ISSUE TITLE
Marketing and Graphic Design - we need schwag!

### ISSUE THREAD

**Issue by daniel-packard** [CenWIDev/sumobot-resources#5]

**Comment by Erik-Bennett** [comment]
If we don't have a graphics pro in the group, we could ask SPASH, Mid-State, or NCTC if they have any students that would take up the project for practical experience.  I know NCTC has a graphics design club that does work in this capacity (free for non-profits) and contact information as well.

**Comment by Erik-Bennett** [comment]
Andrew Somers runs the Graphics Club at NTC; they may be able to help, though from what I gathered when I spoke with him, it depends on the current course offerings.
Somers@ntc.edu

**Comment by daniel-packard** [comment]
looks like greg made a logo that went out in a Create mailer

![image](https://user-images.githubusercontent.com/1051245/54732720-400dc300-4b63-11e9-91b2-c6d53d9001b1.png)

what do you think?

**Comment by Xaphus** [comment]
Took me a while to see the M, kind of reminds me of Big Hero 6 :)

**Comment by Erik-Bennett** [comment]
Can I get a few color fliers printed up for distribution in Marshfield?  10 would suffice.
