### ISSUE TITLE
ELEGOO - Thoughts on these kits?

### ISSUE THREAD

**Issue by Xaphus** [CenWIDev/sumobot-resources#9]
I found these kits while looking for sumo bots.  Does anyone have an option about the value of these kits as a starting point?

https://www.amazon.com/stores/node/14833109011?_encoding=UTF8&field-lbr_brands_browse-bin=ELEGOO&ref_=bl_dp_s_web_14833109011

**Comment by daniel-packard** [comment]
in particular, this one looks like a great deal: 
https://www.amazon.com/ELEGOO-Tracking-Ultrasonic-Intelligent-Educational/dp/B07KPZ8RSZ?ref_=bl_dp_s_web_14833109011

~I'm tempted to spring for one or two to bring to the next thursday meeting~ -- would make a good followup project for "how to arduino"

update: I got one... it was impulse buy territory

**Comment by Erik-Bennett** [comment]
I just picked up an [Elegoo EL-KIT-008 Mega 2560 Project The Most Complete Ultimate Starter Kit]( https://www.amazon.com/EL-KIT-008-Project-Complete-Ultimate-TUTORIAL/dp/B01EWNUUUA) last week. I haven't had much testing time, but the boards look to be well made. The electronics components are serviceable.

The motors in the robot kit _look_ like the same off-the-shelf part that many of other robot kits (including the mBot). They lack encoders (2-wire), limiting their options for other projects (e.g., odometry, use as a digital rotary sensor), but that isn't something needed for sumobots. The reduction gears are almost certainly plastic and not planetary, so they're a likely failure mode. Having four motors and drive wheels will certainly give a torque and traction advantage. [Aliexpress](https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20190313200233&SearchText=robot+motor) has the motors for under $1 if we need addition / replacement motors.

That said, the price is right, imo.

**Comment by Xaphus** [comment]
For encodes, could you make something like this work with them?
https://www.sparkfun.com/products/12629

**Comment by Erik-Bennett** [comment]
I did find [more information on the TT motors](https://www.adafruit.com/product/3777)*.  They should stall before the gears lose mesh or break. We can run a few informal tests to see if they have the torque sufficient for pushing. I've only seen these motors in direct drive configurations, but gearing may be possible, and wheel size changes will offer a similar effect.

There are versions of the same [motor with integrated encoders](https://www.dfrobot.com/product-1457.html). They're 4-wire, so the shield/motor controller needs to have some input connections. After further consideration, there are applicable benefits to motor feedback for sumobots - in particular, measuring motor stall.

There are numerous variants of this motor - [metal geared](https://www.adafruit.com/product/3802), different gear ratios, mount styles, and cases.

More questions than answers at this point, but if the testing results are good, they're a cheap, ubiquitous option.

/* Assuming the yellow TT motors are the same off-the-shelf parts.

**Comment by Xaphus** [comment]
I decided to order one based on everyone's feedback.  I'll probably get a few upgrades, such as encoders and an accelerometer if I get that far in the design.  Thanks for all the feedback.

**Comment by Xaphus** [comment]
We assembled one of these last night.  Here are my thoughts:

- It went together easily and the screws were all in a package and clearly marked
- Some of the exploded diagrams made it difficult to understand, but still a lot better than most kits I've assembled.
- Remote control for the unit worked right out of the box and the batteries were sufficiently charged to play with the robot
- Bluetooth iPhone app worked.  You have to look for the HC1 device.
- The arduino was programmed for you, so you have a nice experience once it's put together.  
- The bot seems to be a bit on the heavy side, but it came with 4 motors.  Overall top speed seemed slower than most of the sumo bots I've seen videos for, might have to upgrade the motors, or tweak the stock program.
- Took two people about 1 and a half hours to build, including disassembly when we screwed up a step :)

Overall, I think this is a really good value proposition.
